# Generated by Django 4.2.3 on 2023-08-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=50)),
                ('task_complete', models.BooleanField(default=False)),
                ('task_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
