# Generated by Django 4.2.3 on 2023-08-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todologin', '0002_dashboarduser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_pics/no_prof_pic.PNG', null=True, upload_to='profile_pics/'),
        ),
    ]
