"""
Django settings for todolist project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

## SECRET KEY UPDATES
from dotenv import load_dotenv
import os
load_dotenv()





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'XXXX'
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# SESSIONS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True # Browser close = reset session

# Application definition

INSTALLED_APPS = [
    'livereload', # livereload for local testing
    'django.contrib.admin',
    'django.contrib.auth', # built in auth support
    'django.contrib.contenttypes', # django content permissions /models support
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # static files
    'todoapp.apps.TodoappConfig', # app # 1
    'todologin.apps.TodologinConfig', # app #2 - login
    'crispy_forms', # https://django-crispy-forms.readthedocs.io/en/latest/install.html#installing-django-crispy-forms
    'crispy_tailwind', # https://pypi.org/project/crispy-tailwind/
    
]
# pip install crispy-tailwind 
# https://pypi.org/project/crispy-tailwind/
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind" # https://pypi.org/project/crispy-tailwind/
CRISPY_TEMPLATE_PACK = 'tailwind'  # https://django-crispy-forms.readthedocs.io/en/latest/install.html#installing-django-crispy-forms

AUTH_USER_MODEL = "todologin.DashboardUser" # new
LOGIN_REDIRECT_URL = '/home' # login redirect  also acceptable "/" or '/' BUT NOT "" or ''
LOGOUT_REDIRECT_URL = '/login' # logout redirect

MIDDLEWARE = [
    'livereload.middleware.LiveReloadScript', # livereload for local testing
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # manage sessions across requests
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # associates users w/ requests using ressions
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'todolist.urls' # whre our root routes are established

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'todolist.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/ # location of time zones

LANGUAGE_CODE = 'en-us' # our language

TIME_ZONE = 'America/New_York' # dev time zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/' 

### {11a} https://stackoverflow.com/a/58394924/22411012
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'todolist/static/')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#### {11a}

### {12a - refactor for IMGs - https://youtu.be/CA5duCGDSUE }
#https://docs.djangoproject.com/en/4.2/ref/models/fields/
MEDIA_URL = 'media/' # created by 1st user upload
MEDIA_ROOT = os.path.join(BASE_DIR, 'todolist/media')

### {12a - refactor for IMGs - https://youtu.be/CA5duCGDSUE }

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


